include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Avoid empty catch blocks
    empty_catches: true
    
    # Prefer const with constant constructors
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Use proper types
    always_specify_types: false
    avoid_types_on_closure_parameters: true
    
    # Use proper naming
    camel_case_types: true
    library_names: true
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    
    # Documentation
    public_member_api_docs: false
    
    # Best practices
    avoid_print: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    prefer_final_fields: true
    unnecessary_this: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_collection_literals: true
    avoid_function_literals_in_foreach_calls: true
    prefer_iterable_whereType: true
    unnecessary_null_in_if_null_operators: true
    prefer_conditional_assignment: true
    prefer_if_null_operators: true
